model:
  image_size: 512
  patch_size: 4
  in_channels: 3
  embed_dim: 96
  ape: True
  num_classes: 9
train:
  seed: 0
  # TODO
  optim: Adam
  warmup: 20
  warmup_lr: 1e-6
  max_epoch: 200
  max_grad_norm: 10
  weight_decay: 0.0002
  lr: 0.0001